<?php
/**
 * Plugin Name: Chunk Your CSV 
 * Plugin URI: https://github.com/woodwardtw/
 * Description: Parses CSV from Google Folder generated by that folder script
 * Version: 1.1
 * Author: Tom Woodward
 * Author URI: http://bionicteaching.com
 * License: GPL2
 */
 
 /*   2016 Tom  (email : bionicteaching@gmail.com)
 
 	This program is free software; you can redistribute it and/or modify
 	it under the terms of the GNU General Public License, version 2, as 
 	published by the Free Software Foundation.
 
 	This program is distributed in the hope that it will be useful,
 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 	GNU General Public License for more details.
 
 	You should have received a copy of the GNU General Public License
 	along with this program; if not, write to the Free Software
 	Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */
 
//[csvToList url="YourFolderID" sol="Grid or List" type="" ]
 
function sol_shortcode($atts, $content=null) {
    extract(shortcode_atts( array(
         'file' => '',
         'sol' => '',
         'type' => '',
    ), $atts)); 
    $return_string = '<ul>';
    $substrLength = strlen($sol);
            $csv = array_map('str_getcsv', file($file));
            array_walk($csv, function(&$a) use ($csv) {
            $a = array_combine($csv[0], $a);
                                    });
            foreach($csv as $item) {
                $name = $item['Name'];
                $short = substr($name, 0, $substrLength);
                $download = $item['Download'];
                $description = $item['Description'];
                $folder = $item['Folder'];
                $preview = $item['URL'];
                if ($short == $sol && $folder == $type){
                $return_string .=  '<li><a href="' . $download . '">' . $name . '</a> - ' . $description . ' - <a href="' . $preview . '">preview</a></li>';
                }
            }
   $return_string .= '</ul>';
   return $return_string;
}
add_shortcode( 'csvToList', 'sol_shortcode' );
