<?php
/**
 * Plugin Name: Chunk Your CSV 
 * Plugin URI: https://github.com/woodwardtw/csvtToSol/blob/master/csvToSol.php
 * Description: Parses CSV from Google Folder generated by that folder script //[csvToList file="URL" sol="stem" type="type" ]

 * Version: 1.7
 * Author: Tom Woodward
 * Author URI: http://bionicteaching.com
 * License: GPL2
 */
 
 /*   2016 Tom  (email : bionicteaching@gmail.com)
 
    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License, version 2, as 
    published by the Free Software Foundation.
 
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
 
    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */
 
//[csvToList file="YourFolderID" sol="" type=""]
add_action('init','remove_wpautop',201);

function remove_wpautop() {
    remove_filter ('acf_the_content', 'wpautop');
    remove_filter( 'the_content', 'wpautop' );

}  
 
function sol_shortcode($atts, $content=null) {
    extract(shortcode_atts( array(
         'file' => '', //file URL
         'sol' => '', //SOL needed
         'type' => '', //type specified
    ), $atts)); 
    
    $substrLength = strlen($sol); //how long is the SOL 
            $cleanFile = preg_replace('/&amp;/', '&', $file);  
            $csv = array_map('str_getcsv', file($cleanFile));
            array_walk($csv, function(&$a) use ($csv) {
            $a = array_combine($csv[0], $a);
                                    });
            $return_string = NULL;
            $i = 0;         
            foreach($csv as $item) {
                $name = $item['Name'];
                $folder = $item['FolderB']; //gets enclosing folder title     
                $fullSOL = $item['FolderA'];           
                $short = substr($fullSOL, 0, $substrLength); //start the substring selection after the SOL length
                $download = $item['Download'];
                $description = $item['Description'];
                $preview = $item['URL'];
                //if the $short variable = the requested shortcode SOL and the $folder = the requested type then spit it out
                if ($short == $sol && $folder == $type){
                    if ($i == 0){
                        $return_string .= '<div class="skiplinks"><h2>' . $folder .'</h2><ul>';
                    }
                $return_string .=  '<li><a href="' . $preview . '">' . $name . '</a> - ' . $description . ' - <a href="' . $download . '">preview</a></li>';
                $i++;
                }                
            }
    if ($i>0) {
        $return_string .= '</ul></div>'; 

   return  $return_string ;
    }
}
add_shortcode( 'csvToList', 'sol_shortcode' );
